//
// Created by marcel on 11/16/25.
//

#ifndef SCREENCONTROLLER_CONNECTIONSTATE_H
#define SCREENCONTROLLER_CONNECTIONSTATE_H


enum class ConnectionState {
  STARTING,
  NOT_CONNECTED,
  CONNECTED,
  SENDING,
  DISCONNECTED,
};

#endif  // SCREENCONTROLLER_CONNECTIONSTATE_H
